[project]
name = "backend"
version = "0.1.0"
description = "API development for Flight Planning services"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
   "fastapi[standard]>=0.139.2",
   "aiosqlite>=0.22.1",
   "alembic>=1.18.4",
   "argon2-cffi>=25.1.0",
   "bcrypt>=4.0.0",
   "black>=26.5.1",
   "email-validator>=2.3.0",
   "fastapi[standard]>=0.136.3",
   "httpx>=0.28.1",
   "jose>=1.0.0",
   "passlib>=1.7.4",
   "psycopg2-binary>=2.9.12",
   "pyjwt>=2.13.0",
   "pytest>=9.0.3",
   "pytest-asyncio>=1.4.0",
   "python-dotenv>=1.2.2",
   "python-jose>=3.5.0",
   "python-multipart>=0.0.30",
   "requests>=2.34.2",
   "ruff>=0.15.15",
   "slowapi>=0.1.9",
   "sqlalchemy>=2.0.50",
   "import-ipynb>=0.2",
   "jupyter>=1.1.1",
   "matplotlib>=3.11.0",
   "numpy>=2.5.0",
   "pandas>=3.0.3",
   "scipy>=1.18.0",
   "docxtpl>=0.20.2",
   "uvicorn[standard]>=0.51.0",
   "pyshorteners>=1.0.1",
   "openpyxl>=3.1.5",
   "pypdf2>=3.0.1",
   "xlwings>=0.36.13",
   "pyyaml>=6.0.3"]
